# mysql -u root -p < /var/lib/mysql/dronevlieger.sql
---
version: "3"

services:
  php:
    build: 
      context: ./bin/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    restart: 'always'
    depends_on:
      - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    ports:
      - "80" #auto port control for multiple containers
      - "443" #auto port control for multiple containers
      #- "${HOST_MACHINE_UNSECURE_HOST_PORT}:80" #specific ports for single container
      #- "${HOST_MACHINE_SECURE_HOST_PORT}:443" #specific ports for single container
    links:
      - php
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${NGINX_LOG_DIR-./logs/nginx}:/var/log/nginx/
      - ${NGINX_CONF-./config/nginx/nginx.conf}:/etc/nginx/nginx.conf

  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-${DATABASE}'
    restart: 'always'
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    ports:
      - "3306" #auto port control for multiple containers
      #- "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306" #specific ports for single container
    volumes: 
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - "80" #auto port control for multiple containers
      #- '${HOST_MACHINE_PMA_PORT}:80' #specific ports for single container
    volumes: 
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini



  redis:
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    image: redis:latest
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"

networks:
  ${COMPOSE_PROJECT_NAME}-network:
    name: "${COMPOSE_PROJECT_NAME}-network"
    driver: bridge
