version: "3"

services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: "${COMPOSE_PROJECT_NAME}-${PHPVERSION}"
    restart: ${RESTART}
    depends_on:
      - database
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      - APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT-/var/www/html}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ
      - PUID
      - PGID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL}`) || Host(`www.${URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${CERTRESOLVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-www-to-non-www@file,middlewares-compress@file"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadBalancer.server.port=80"

  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    restart: ${RESTART}
    volumes:
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ
      - PUID
      - PGID

  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis:latest

  traefik:
    image: traefik:latest
    container_name: "${COMPOSE_PROJECT_NAME}-traefik"
    restart: ${RESTART}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TRAEFIK_ACME_DIR-./config/traefik/acme}:/letsencrypt"
      - "${TRAEFIK_RULES_DIR-./config/traefik/rules:/rules"
      - "${TRAEFIK_TRAEFIK_CONF-./config/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
    environment:
      - TZ
      - PUID
      - PGID
