---
global:
  sendAnonymousUsage: false
  #checkNewVersion: false

api:
  #insecure: true
  dashboard: true
  #debug: true

pilot:
  dashboard: false

log:
  level: "ERROR"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    swarmMode: false
  file:
    directory: /rules
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  lets-encrypt:
    acme:
      #caserver: https://acme-staging-v02.api.letsencrypt.org/directory #only for debug
      email: email@email.com
      storage: /letsencrypt/acme.json
      tlschallenge: true
      # httpChallenge:
      #   entrypoint: web
